services:
  perf-konifer:
    container_name: perf_konifer
     # If building locally, comment out image: and uncomment the section below
#    build:
#      context: .
#      dockerfile: Dockerfile
    image: ghcr.io/dmaiken/konifer:latest
    ports:
      - "8080:8080"
    volumes:
      - ./konifer.conf:/app/config/konifer.conf
    environment:
      PG_PASSWORD: konifer_password
      S3_SECRET_KEY: minio_secret_key
    depends_on:
      perf-postgres:
        condition: service_healthy
      perf-minio:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: 2.0
          memory: 512M
    networks:
      - konifer-perf-net

  perf-postgres:
    image: postgres:17-alpine
    container_name: perf_konifer_postgres
    environment:
      POSTGRES_USER: konifer_user
      POSTGRES_PASSWORD: konifer_password
      POSTGRES_DB: konifer
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U konifer_user -d konifer"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - konifer-perf-net

  perf-minio:
    image: minio/minio
    container_name: perf_konifer_minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000" # S3 API Port
      - "9001:9001" # Web Console Port
    environment:
      MINIO_ROOT_USER: minio_admin
      MINIO_ROOT_PASSWORD: minio_secret_key
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 20s
      retries: 3
    networks:
      - konifer-perf-net

  # MinIO starts empty. This container creates the default bucket automatically.
  createbuckets:
    image: minio/mc
    depends_on:
      perf-minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://perf-minio:9000 minio_admin minio_secret_key;
      /usr/bin/mc mb myminio/assets;
      /usr/bin/mc anonymous set public myminio/assets;
      exit 0;
      "
    networks:
      - konifer-perf-net

networks:
  konifer-perf-net:
    driver: bridge
